### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by hategan**
More graceful transfer error handling. girderfs must also be updated for mounts to show this.

### CODE REVIEW

**Comment by Xarthisius** [comment]
For other testers, I roughly followed this scenario:

1. Deploy this along with https://github.com/whole-tale/girder_wholetale/pull/339 and https://github.com/whole-tale/girderfs/pull/12. Please note that latest https://github.com/whole-tale/deploy-dev/commit/a62475abac987edc16c2bc7633ad1d7734f20955 uses girderfs from source, so you might need to update it too.
2. Register `doi:10.18126/M2301J`
3. Create a Tale based on Jupyter Notebook
4. Add `Twin-mediated Crystal Growth: an Enigma Resolved/{globus_metadata.json,data/metadata.json}` to Tale's external data.
5. Run the Tale
6. Open a Terminal in Jupyter Notebook
7. `cd ../data`
8. `cat globus_metadata.json` and verify that it returns json content.
9. Turn off the Wi-Fi (or unplug net cable ;-) )
10. `cat metadata.json` and verify that after a while you get IOError

Note: pending changes suggested in my [comment](https://github.com/whole-tale/girderfs/pull/12#discussion_r313477887) the following should also work:
11. Turn on the Wi-Fi.
12. `cat metadata.json` again (you may need to repeat it more than once, after waiting 2-10s) and verify that you get proper content and no error.

**Comment by hategan** [comment]
> There are some parts that made my brain tingle, cause it detected java (`self.getTransferredByteCount()` instead of just `self.flen`, same with all those getters in `TransferException`) but it LGTM and works as advertised!

getTransferedByteCount more clear than flen (file length?)!

TransferException is needed to communicate to callers whether an error is temporary (as in Globus hit some issue and will retry) or final, as in all hope is lost. But TransferException doesn't represent a root cause, so, if we're to display the actual problem to the user, we need the chaining.

It can be argued that what TransferException does can be replaced by a call to the transfer manager. However, there may be other kinds of exceptions in possibly badly implemented transfer handlers which, wisdom says, we should catch. So perhaps there shouldn't be two separate mechanisms for signalling an exceptional condition.

**Comment by Xarthisius** [comment]
> getTransferedByteCount more clear than flen (file length?)!

It's not about the name, it's about the fact that you're using getter.

> TransferException is needed to communicate to callers whether an error is temporary (as in Globus hit some issue and will retry) or final, as in all hope is lost. But TransferException doesn't represent a root cause, so, if we're to display the actual problem to the user, we need the chaining.
> 
> It can be argued that what TransferException does can be replaced by a call to the transfer manager. However, there may be other kinds of exceptions in possibly badly implemented transfer handlers which, wisdom says, we should catch. So perhaps there shouldn't be two separate mechanisms for signalling an exceptional condition.

Same here. `TransferException` as-is is perfectly fine and justified. It's just getting public class attributes via getters that trips me ;-)

**Comment by hategan** [comment]
I guess I should have used property decorators instead. But that just irks me because it seems like unnecessary complexity meant to make things pythonesque by avoiding explicit getters and setters.  It makes it hard for the brain to jump to the right place when trying to figure out what happens when you see, e.g., x.flen in the code. And it's all because of poor design in which the idea of having stable yet portable interfaces came as an afterthought.

Now, I could be persuaded that a layer of indirection is fine if it got me something in the way of abstraction (aka. less code). But there isn't less code with @property. So it's a hack to solve a bad habit that didn't have to be there in the first place. That said, it's fine. Python was designed for quickly writing glue code, not to optimize the software engineering process of large projects, and I'm fine with that as long as we acknowledge it and its consequences.

Ok, I'm done ranting :)

**Pull request merged**
